import type { Movie, Series } from '../../api'

export const makeMovie = (overrides: Partial<Movie> = {}): Movie => ({
  id: 'movie-1',
  extId: 'tt123',
  provider: 'omdb',
  title: 'Some Movie',
  poster: 'http://localhost/poster.jpg',
  year: 2020,
  rating: 7.5,
  language: 'English',
  genre: 'Drama',
  reason: 'because',
  seen: null,
  seenRating: null,
  seenComment: null,
  userId: 'user-1',
  private: false,
  scheduled: null,
  tags: null,
  extra: {},
  ...overrides,
})

export const makeSeries = (overrides: Partial<Series> = {}): Series => ({
  id: 'series-1',
  extId: 'tt456',
  provider: 'omdb',
  title: 'Some Series',
  poster: null,
  year: 2021,
  season: 1,
  seasonHistory: null,
  rating: 8,
  language: 'English',
  genre: 'Sci-Fi',
  reason: null,
  seen: null,
  seenRating: null,
  seenComment: null,
  userId: 'user-1',
  private: false,
  scheduled: null,
  tags: null,
  extra: {},
  ...overrides,
})
